# task config
task: hierarchical_multiplecombat_1v1_style

# simulation config
sim_freq: 60
agent_interaction_steps: 12 # step 0.2s

# termination config
max_steps: 1000             # episode length: 200s
altitude_limit: 2500
acceleration_limit_x: 10.0
acceleration_limit_y: 10.0
acceleration_limit_z: 10.0

# aircraft config
aircraft_configs: {
  A0100: {
    color: Red,
    model: f16,
    init_state: {
      ic_long_gc_deg: 120.1,
      ic_lat_geod_deg: 60.02,
      ic_h_sl_ft: 25000,
      ic_psi_true_deg: 0.0,
      ic_u_fps: 800.0,
    },
  },
  A0200: {
    color: Red,
    model: f16,
    init_state: {
      ic_long_gc_deg: 119.9,
      ic_lat_geod_deg: 60.01,
      ic_h_sl_ft: 25000,
      ic_psi_true_deg: 0.0,
      ic_u_fps: 800.0,
    },
  },
  A0300: {
    color: Red,
    model: f16,
    init_state: {
      ic_long_gc_deg: 120.02,
      ic_lat_geod_deg: 60.0,
      ic_h_sl_ft: 25000,
      ic_psi_true_deg: 0.0,
      ic_u_fps: 800.0,
    },
  },
  A0400: {
    color: Red,
    model: f16,
    init_state: {
      ic_long_gc_deg: 120.16,
      ic_lat_geod_deg: 60.05,
      ic_h_sl_ft: 25000,
      ic_psi_true_deg: 0.0,
      ic_u_fps: 800.0,
    },
  },
  B0100: {
    color: Blue,
    model: f16,
    init_state: {
      ic_h_sl_ft: 20000,
      ic_long_gc_deg: 120.0,
      ic_lat_geod_deg: 60.15,
      ic_psi_true_deg: 180.0,
      ic_u_fps: 800.0,
    },
  },
  B0200: {
    color: Blue,
    model: f16,
    init_state: {
      ic_h_sl_ft: 20000,
      ic_long_gc_deg: 120.03,
      ic_lat_geod_deg: 60.15,
      ic_psi_true_deg: 180.0,
      ic_u_fps: 800.0,
    },
  },
  B0300: {
    color: Blue,
    model: f16,
    init_state: {
      ic_h_sl_ft: 20000,
      ic_long_gc_deg: 120.06,
      ic_lat_geod_deg: 60.1,
      ic_psi_true_deg: 180.0,
      ic_u_fps: 800.0,
    },
  },
  B0400: {
    color: Blue,
    model: f16,
    init_state: {
      ic_h_sl_ft: 20000,
      ic_long_gc_deg: 119.93,
      ic_lat_geod_deg: 60.1,
      ic_psi_true_deg: 180.0,
      ic_u_fps: 800.0,
    },
  },
}

# reward config
reward_config: {
  altitude_reward: {
    target_altitude: 20000,
    altitude_tolerance: 5000,
    reward_scale: 1.0,
  },
  posture_reward: {
    reward_scale: 1.0,
  },
  event_driven_reward: {
    reward_scale: 1.0,
  },
}

# termination config
termination_config: {
  safe_return: {
    return_altitude: 20000,
    return_distance: 50000,
    return_tolerance: 5000,
  },
  extreme_state: {
    max_altitude: 30000,
    min_altitude: 1000,
    max_acceleration: 10.0,
  },
  overload: {
    max_overload: 10.0,
  },
  low_altitude: {
    min_altitude: 1000,
  },
  timeout: {
    max_steps: 1000,
  },
} 